# Generated by Django 3.1.2 on 2020-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerating',
            name='user_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
