# Generated by Django 3.1.2 on 2020-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='does_joe_like',
            field=models.BooleanField(default=True),
        ),
    ]
