# Generated by Django 3.1.2 on 2020-11-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_game_does_joe_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='does_joe_like',
        ),
    ]
